spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    #################以下是druid增加的配置#################
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 参考 https://github.com/alibaba/druid/wiki/DruidDataSource%E9%85%8D%E7%BD%AE%E5%B1%9E%E6%80%A7%E5%88%97%E8%A1%A8
      # 初始化大小，最小，最大
      initialSize: 40
      minIdle: 20
      maxActive: 100
      # 配置获取连接等待超时的时间
      maxWait: 300
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      #  用来检测连接是否有效的sql，要求是一个查询语句，常用select 'x'。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，'stat'用于统计监控信息，'wall'用于防火墙。
      # DruidFilterConfiguration定义了系统中所有的filter
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录;启用加密，配置公钥。
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 参考 https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_StatFilter
      # filters: mergeStat 等价于 filters: stat + ConnectionProperties: druid.stat.mergeSql = true
      # connectionProperties：druid.stat.slowSqlMillis = 5000 等价于下面配置
#      filter:
#        stat:
#          slow-sql-millis: 5000

      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
      # 配置监控服务器，地址为localhost:8080/druid
      stat-view-servlet:
        enabled: true
        reset-enable: true
        login-username: freedom
        login-password: freedom

  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10s
    password:
    # 默认是lettuce连接池
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 9
        max-wait: 1000s
