spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    # 驼峰法
    map-underscore-to-camel-case: true
    cache-enabled: false
  type-aliases-package: com.freedom.springbootdevtemplate
